version: '3.7'

services:
  nginx:
    image: nginx
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    dns: 8.8.8.8
    ports:
      - "80:80"
    environment:
      NODE_ENV: development